version: '3'

services:
  jenkins:
    container_name: jenkins  # 设置容器的名称
    hostname: jenkins  # 设置容器的主机名
    image: jenkins-xujs/1.0
    restart: always
    #    network_mode: host
    ports:
      - "8088:8080"
      - "50000:50000"
      - "8089:8089"
    volumes:
      - /usr/local/docker/jenkins:/var/jenkins_home
    environment:
      - TZ=Asia/Shanghai

