/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class work_jni_Hello */

#ifndef _Included_work_jni_Hello
#define _Included_work_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_jni_Hello
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_work_jni_Hello_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
