spring:
  application:
    name: Java-Study
  redis:
    port: 6379
    host: 10.25.10.216
    password: Netvine123#@!
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
server:
  port: 9003
  address: 0.0.0.0
